@startjson
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "Service",
    "description": "Service flavor type",
    "properties": {
        "name": {
            "type": "string",
            "description": "Name of the service"
        },
        "characteristics": {
            "type": "string",
            "description": "JSON object containing service characteristics. This is a string to allow for flexibility in the schema definition."
        }
    }
}
@endjson